<template>
  <v-html>
<div class="Section0"  style="layout-grid:15.6000pt;" ><p class=MsoNormal  style="text-align:left;" ><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" ><o:p>&nbsp;</o:p></span></p><p class=MsoNormal  style="text-align:left;" ><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" >08:30 - 08:50 ------------------------Opening Remarks---------------------------</span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" ><o:p></o:p></span></p><p class=MsoNormal  style="text-align:left;" ><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:16.0000pt;mso-font-kerning:1.0000pt;" >Keynote Session 1</span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:16.0000pt;mso-font-kerning:1.0000pt;" ><o:p></o:p></span></p><p class=MsoNormal  style="text-align:left;" ><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" >Chair: </span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" ><font face="等线" >包云岗</font></span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" ><o:p></o:p></span></p><p class=MsoNormal  style="text-align:left;" ><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" >08:50 - 09:20 Topic: </span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" ><font face="等线" >高性能固态存储系统的构建</font></span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" ><o:p></o:p></span></p><p class=MsoNormal  style="text-indent:63.0000pt;mso-char-indent-count:6.0000;text-align:left;" ><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" >Speaker: </span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" ><font face="等线" >舒继武</font></span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" ><o:p></o:p></span></p><p class=MsoNormal  style="text-align:left;" ><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" >09:20 - 09:50 Topic: Project Organon: Building the Next Generation AI Software Infrastructure</span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" ><o:p></o:p></span></p><p class=MsoNormal  style="text-indent:63.0000pt;mso-char-indent-count:6.0000;text-align:left;" ><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" >Speaker: 张霖涛</span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" ><o:p></o:p></span></p><p class=MsoNormal  style="text-align:left;" ><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" >0</span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" >9:50 </span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" >&#8211; 10</span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" >:00 ------------------------------茶歇--------------------------------</span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" >-</span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" ><o:p></o:p></span></p><p class=MsoNormal  style="text-align:left;" ><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:16.0000pt;mso-font-kerning:1.0000pt;" >Keynote Session 2</span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:16.0000pt;mso-font-kerning:1.0000pt;" ><o:p></o:p></span></p><p class=MsoNormal  style="text-align:left;" ><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" >Chair: </span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" ><font face="等线" >谭光明</font></span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" ><o:p></o:p></span></p><p class=MsoNormal  style="text-align:left;" ><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" >10:00 - 10:30 Topic: TBD</span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" ><o:p></o:p></span></p><p class=MsoNormal  style="text-indent:52.5000pt;mso-char-indent-count:5.0000;text-align:left;" ><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" >&nbsp;&nbsp;Speaker: 卢山</span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" ><o:p></o:p></span></p><p class=MsoNormal  style="text-align:left;" ><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" >10:30 - 11:00 Topic: </span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" >AI工程的系统优化在阿里</span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" ><font face="等线" >云</font></span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" >PAI平台</span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" ><font face="等线" >的</font></span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" ><font face="等线" >实践</font></span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" ><o:p></o:p></span></p><p class=MsoNormal  style="text-indent:52.5000pt;mso-char-indent-count:5.0000;text-align:left;" ><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" >&nbsp;&nbsp;Speaker: 林伟</span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" ><o:p></o:p></span></p><p class=MsoNormal  style="text-align:left;" ><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:16.0000pt;mso-font-kerning:1.0000pt;" >Paper Session 1: OSDI</span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:16.0000pt;mso-font-kerning:1.0000pt;" ><o:p></o:p></span></p><p class=MsoNormal  style="text-align:left;" ><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" >11:00 - 11:20 Topic: Rammer: Enabling Holistic Deep Learning Compiler Optimizations with rTasks</span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" ><o:p></o:p></span></p><p class=MsoNormal  style="text-indent:52.5000pt;mso-char-indent-count:5.0000;text-align:left;" ><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" >&nbsp;&nbsp;Speaker: Lingxiao Ma</span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" ><o:p></o:p></span></p><p class=MsoNormal  style="text-align:left;" ><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" >11:20 - 11:40 Topic: Write Dependency Disentanglement with HORAE</span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" ><o:p></o:p></span></p><p class=MsoNormal  style="text-indent:52.5000pt;mso-char-indent-count:5.0000;text-align:left;" ><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" >&nbsp;&nbsp;Speaker: Xiaojian Liao</span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" ><o:p></o:p></span></p><p class=MsoNormal  style="text-align:left;" ><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" >11:40 - 12:00 Topic: Retiarii: A Deep Learning Exploratory-Training Framework</span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" ><o:p></o:p></span></p><p class=MsoNormal  style="text-indent:52.5000pt;mso-char-indent-count:5.0000;text-align:left;" ><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" >&nbsp;&nbsp;Speaker: Quanlu Zhang</span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" ><o:p></o:p></span></p><p class=MsoNormal  style="text-align:left;" ><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" ><o:p>&nbsp;</o:p></span></p><p class=MsoNormal  style="text-align:left;" ><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" >12:00 </span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" >&#8211; 1</span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" >:30 ------------------------------午餐--------------------------------</span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" >--</span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" ><o:p></o:p></span></p><p class=MsoNormal  style="text-align:left;" ><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:16.0000pt;mso-font-kerning:1.0000pt;" >Paper Session 2: Storage</span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:16.0000pt;mso-font-kerning:1.0000pt;" ><o:p></o:p></span></p><p class=MsoNormal  style="text-align:left;" ><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" >13:30 - 13:50 Topic: Spool: Reliable Virtualized NVMe Storage Pool in Public Cloud Infrastructure</span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" ><o:p></o:p></span></p><p class=MsoNormal  style="margin-left:42.0000pt;text-align:left;" ><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" >&nbsp;&nbsp;&nbsp;&nbsp;Speaker: Shuai Xue</span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" ><o:p></o:p></span></p><p class=MsoNormal  style="text-align:left;" ><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" >13:50 - 14:10 Topic: HDDse: Enabling High-Dimensional Disk State Embedding for Generic Failure Detection System of Heterogeneous Disks in Large Data Centers</span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" ><o:p></o:p></span></p><p class=MsoNormal  style="text-indent:63.0000pt;mso-char-indent-count:6.0000;text-align:left;" ><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" >Speaker: Ji Zhang</span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" ><o:p></o:p></span></p><p class=MsoNormal  style="text-align:left;" ><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" >14:10 - 14:30 Topic: Improving System Performance via Fine-Grained In-DRAM Data Relocation and Caching</span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" ><o:p></o:p></span></p><p class=MsoNormal  style="text-indent:63.0000pt;mso-char-indent-count:6.0000;text-align:left;" ><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" >Speaker: Yaohua Wang</span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" ><o:p></o:p></span></p><p class=MsoNormal  style="text-align:left;" ><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:16.0000pt;mso-font-kerning:1.0000pt;" >Paper Session 3 Performance and Reliability</span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:16.0000pt;mso-font-kerning:1.0000pt;" ><o:p></o:p></span></p><p class=MsoNormal  style="text-align:left;" ><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" >14:30 - 14:50 Topic: Effective Detection of Sleep-in-atomic-context Bugs in the Linux Kernel </span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" ><o:p></o:p></span></p><p class=MsoNormal  style="text-indent:63.0000pt;mso-char-indent-count:6.0000;text-align:left;" ><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" >Speaker: Jia-Ju Bai</span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" ><o:p></o:p></span></p><p class=MsoNormal  style="text-align:left;" ><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" >14:50 - 15:10 Topic: Alita: Comprehensive Performance Isolation through Bias Resource Management for Public Clouds</span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" ><o:p></o:p></span></p><p class=MsoNormal  style="text-indent:63.0000pt;mso-char-indent-count:6.0000;text-align:left;" ><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" >Speaker: Quan Chen</span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" ><o:p></o:p></span></p><p class=MsoNormal  style="text-align:left;" ><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" >15:10 - 15:30 Topic: Characterizing Serverless Platforms with ServerlessBench</span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" ><o:p></o:p></span></p><p class=MsoNormal  style="text-indent:63.0000pt;mso-char-indent-count:6.0000;text-align:left;" ><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" >Speaker: Dong Du</span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" ><o:p></o:p></span></p><p class=MsoNormal  style="text-align:left;" ><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" >15</span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" >:30 </span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" >&#8211; 15</span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" >:40</span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" >&nbsp;</span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" >-------------------------------茶歇--------------------------------</span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" ><o:p></o:p></span></p><p class=MsoNormal  style="text-align:left;" ><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:16.0000pt;mso-font-kerning:1.0000pt;" >Paper Session 4 Security</span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:16.0000pt;mso-font-kerning:1.0000pt;" ><o:p></o:p></span></p><p class=MsoNormal  style="text-align:left;" ><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" >15:40 - 16:00 Topic: ZeroSpy: Exploring Software Inefficiency with Redundant Zeros</span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" ><o:p></o:p></span></p><p class=MsoNormal  style="text-indent:63.0000pt;mso-char-indent-count:6.0000;text-align:left;" ><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" >Speaker: Xin You</span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" ><o:p></o:p></span></p><p class=MsoNormal  style="text-align:left;" ><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" >16:00 - 16:20 Topic: PDiff: Semantic-based Patch Presence Testing for Downstream Kernels</span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" ><o:p></o:p></span></p><p class=MsoNormal  style="text-indent:63.0000pt;mso-char-indent-count:6.0000;text-align:left;" ><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" >Speaker: Zheyue Jiang</span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" ><o:p></o:p></span></p><p class=MsoNormal  style="text-align:left;" ><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" >16:20 - 16:40 Topic: Detecting Kernel Refcount Bugs with Two-Dimensional Consistency Checking</span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" ><o:p></o:p></span></p><p class=MsoNormal  style="text-indent:63.0000pt;mso-char-indent-count:6.0000;text-align:left;" ><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" >Speaker: Xin Tan</span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" ><o:p></o:p></span></p><p class=MsoNormal  style="text-align:left;" ><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:16.0000pt;mso-font-kerning:1.0000pt;" >Paper Session 5 Application</span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:16.0000pt;mso-font-kerning:1.0000pt;" ><o:p></o:p></span></p><p class=MsoNormal  style="text-align:left;" ><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" >16:40 - 17:00 Topic: A Locality-Aware Energy-Efficient Accelerator for Graph Mining Applications</span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" ><o:p></o:p></span></p><p class=MsoNormal  style="text-indent:63.0000pt;mso-char-indent-count:6.0000;text-align:left;" ><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" >Speaker: Pengcheng Yao</span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" ><o:p></o:p></span></p><p class=MsoNormal  style="text-align:left;" ><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" >17:00 - 17:20 Topic: BORA: A Bag Optimizer for Robotic Analysis</span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" ><o:p></o:p></span></p><p class=MsoNormal  style="text-indent:63.0000pt;mso-char-indent-count:6.0000;text-align:left;" ><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" >Speaker: Jian Zhang</span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" ><o:p></o:p></span></p><p class=MsoNormal  style="text-align:left;" ><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" >17:20 - 17:40 Topic: Ptolemy: Architecture Support for Robust Deep Learning</span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" ><o:p></o:p></span></p><p class=MsoNormal  style="text-indent:63.0000pt;mso-char-indent-count:6.0000;text-align:left;" ><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" >Speaker: Yuxian Qiu</span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" ><o:p></o:p></span></p><p class=MsoNormal  style="text-align:left;" ><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" ><o:p>&nbsp;</o:p></span></p><p class=MsoNormal  style="text-align:left;" ><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" >------------</span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" >------------------------------晚宴--------------------------------</span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" >-</span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" ><o:p></o:p></span></p><p class=MsoNormal  style="text-align:left;" ><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:16.0000pt;mso-font-kerning:1.0000pt;" >Keynote </span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:16.0000pt;mso-font-kerning:1.0000pt;" >Session 3</span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:16.0000pt;mso-font-kerning:1.0000pt;" ><o:p></o:p></span></p><p class=MsoNormal  style="text-align:left;" ><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" >Chair: </span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" ><o:p></o:p></span></p><p class=MsoNormal  style="text-align:left;" ><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" >09:00 - 09:30 Topic: </span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" ><font face="等线" >计算机系统研究的一些体会</font></span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" ><o:p></o:p></span></p><p class=MsoNormal  style="text-indent:63.0000pt;mso-char-indent-count:6.0000;text-align:left;" ><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" >Speaker: </span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" ><font face="等线" >陈海波</font></span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" ><o:p></o:p></span></p><p class=MsoNormal  style="text-align:left;" ><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" >09:30 &#8211; 10:00 Topic: HPC + AI + 物理模型：智能超算应用的新发展</span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" ><o:p></o:p></span></p><p class=MsoNormal  style="text-indent:63.0000pt;mso-char-indent-count:6.0000;text-align:left;" ><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" >Speaker: </span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" ><font face="等线" >贾伟乐</font></span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" ><o:p></o:p></span></p><p class=MsoNormal  style="text-align:left;" ><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" >10:00 &#8211; 10:10 </span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" >------------------------------茶歇--------------------------------</span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" ><o:p></o:p></span></p><p class=MsoNormal  style="text-align:left;" ><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:16.0000pt;mso-font-kerning:1.0000pt;" ><font face="等线" >经验分享环节</font></span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:16.0000pt;mso-font-kerning:1.0000pt;" ><o:p></o:p></span></p><p class=MsoNormal  style="text-align:left;" ><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" >Chair: </span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" ><font face="等线" >李诚</font></span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" ><o:p></o:p></span></p><p class=MsoNormal  style="text-align:left;" ><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" >10:10 - 10:30新星奖获得者</span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" >1</span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" ><o:p></o:p></span></p><p class=MsoNormal  style="text-align:left;" ><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" >10:30 - 10:50新星奖获得者2</span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" ><o:p></o:p></span></p><p class=MsoNormal  style="text-align:left;" ><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" >10:50 - 11:10优博奖获得者</span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" >1</span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" ><o:p></o:p></span></p><p class=MsoNormal  style="text-align:left;" ><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" >11:10 - 11:30优博奖获得者</span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" >2</span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" ><o:p></o:p></span></p><p class=MsoNormal  style="text-align:left;" ><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" >11:30 - 12:00 Panel: </span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" ><font face="等线" >陈海波，</font></span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" ><font face="等线" >新星奖获得者</font></span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" >1，</span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" ><font face="等线" >新星奖获得者</font>2</span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" ><font face="等线" >，</font></span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" ><font face="等线" >优博奖获得者</font></span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" >1和</span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" ><font face="等线" >优博奖获得者</font>2</span><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" ><o:p></o:p></span></p><p class=MsoNormal  style="text-align:left;" ><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:16.0000pt;mso-font-kerning:1.0000pt;" ><o:p>&nbsp;</o:p></span></p><p class=MsoNormal  style="text-align:left;" ><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:16.0000pt;mso-font-kerning:1.0000pt;" ><o:p>&nbsp;</o:p></span></p><p class=MsoNormal  style="text-align:left;" ><span style="mso-spacerun:'yes';font-family:等线;mso-bidi-font-family:'Times New Roman';
font-size:10.5000pt;mso-font-kerning:1.0000pt;" ><o:p>&nbsp;</o:p></span></p></div>
  </v-html>

</template>

<script>
  export default {
    name: "Program",
    data: () => ({

    }),

  }

</script>